definitions:
  main.LoginUser:
    properties:
      password:
        description: |-
          Password字段表示登录密码
          bind:"required"表示这个字段是必需的，需要在绑定时提供值
          json:"password"表示在JSON序列化/反序列化时使用的键名
        type: string
      username:
        description: |-
          Username字段表示登录用户名
          bind:"required"表示这个字段是必需的，需要在绑定时提供值
          json:"username"表示在JSON序列化/反序列化时使用的键名
        type: string
    type: object
info:
  contact: {}
paths:
  /loginWithJSON:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: body
        name: string
        schema:
          $ref: '#/definitions/main.LoginUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 用户登录
      tags:
      - 登录认证
swagger: "2.0"
