definitions:
  main.LoginUser:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: body
        name: string
        schema:
          $ref: '#/definitions/main.LoginUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 用户登录
      tags:
      - 登录认证
swagger: "2.0"
