definitions:
  main.JSONResult:
    properties:
      code:
        description: 业务码
        type: integer
      data:
        description: 响应数据
      message:
        description: 响应信息
        type: string
    type: object
  main.LoginResponse:
    properties:
      token:
        type: string
    type: object
  main.LoginUser:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: body
        name: string
        schema:
          $ref: '#/definitions/main.LoginUser'
      produces:
      - application/json
      responses:
        "200":
          description: 响应
          schema:
            allOf:
            - $ref: '#/definitions/main.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/main.LoginResponse'
              type: object
      summary: 用户登录
      tags:
      - 登录认证
swagger: "2.0"
