definitions:
  api.JSONResult:
    properties:
      code:
        description: 业务码
        type: integer
      data:
        description: 响应数据
      message:
        description: 响应信息
        type: string
    type: object
info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Ping 测试接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.JSONResult'
      summary: ping
      tags:
      - 通用
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
